# Pipeline

In [14]:
from pathlib import Path

from lana_nlp.preprocessing.data_loader import LyricsDataLoader
from lana_nlp.preprocessing.text_cleaner import TextCleaner
from lana_nlp.features.lyrics_features import LyricsFeatures
from lana_nlp.analysis.lyrics_analyzer import LyricsAnalyzer

## Load the lyrics

In [15]:
loader = LyricsDataLoader(
    Path("../data/raw/lyrics.csv")
)

df = loader.load()

print(df.shape)
df.head()

(154, 5)

,artist,album,song,year,lyrics
0,Lana Del Rey,Sirens,Drive By,2006,There was a drive-by Sunday night\nMost of us ...
1,Lana Del Rey,Sirens,River Road,2006,"Another day is over, another day is done\nAnd ..."
2,Lana Del Rey,Sirens,A Star for Nick,2006,"Well, you know it and I know it, I'm gonna be ..."
3,Lana Del Rey,Sirens,My Momma,2006,My momma wouldn't say you were a nice guy\nBut...
4,Lana Del Rey,Sirens,Bad Disease,2006,"Well, there's somethin' about watchin' a crime..."

## Clean the lyrics (basic)

In [16]:
cleaner = TextCleaner()

df["basic_cleaned_lyrics"] = df["lyrics"].apply(cleaner.basic_clean)
df.head()

,artist,album,song,year,lyrics,basic_cleaned_lyrics
0,Lana Del Rey,Sirens,Drive By,2006,There was a drive-by Sunday night\nMost of us ...,there was a driveby sunday night most of us we...
1,Lana Del Rey,Sirens,River Road,2006,"Another day is over, another day is done\nAnd ...",another day is over another day is done and no...
2,Lana Del Rey,Sirens,A Star for Nick,2006,"Well, you know it and I know it, I'm gonna be ...",well you know it and i know it im gonna be a s...
3,Lana Del Rey,Sirens,My Momma,2006,My momma wouldn't say you were a nice guy\nBut...,my momma wouldnt say you were a nice guy but y...
4,Lana Del Rey,Sirens,Bad Disease,2006,"Well, there's somethin' about watchin' a crime...",well theres somethin about watchin a crime tha...

## NLP cleaned lyrics

In [17]:
df["nlp_cleaned_lyrics"] = df["basic_cleaned_lyrics"].apply(cleaner.nlp_clean)
df.head()

,artist,album,song,year,lyrics,basic_cleaned_lyrics,nlp_cleaned_lyrics
0,Lana Del Rey,Sirens,Drive By,2006,There was a drive-by Sunday night\nMost of us ...,there was a driveby sunday night most of us we...,"[driveby, sunday, night, u, bed, right, turned..."
1,Lana Del Rey,Sirens,River Road,2006,"Another day is over, another day is done\nAnd ...",another day is over another day is done and no...,"[another, day, another, day, done, im, gettin,..."
2,Lana Del Rey,Sirens,A Star for Nick,2006,"Well, you know it and I know it, I'm gonna be ...",well you know it and i know it im gonna be a s...,"[well, know, know, im, gon, na, star, wont, wo..."
3,Lana Del Rey,Sirens,My Momma,2006,My momma wouldn't say you were a nice guy\nBut...,my momma wouldnt say you were a nice guy but y...,"[momma, wouldnt, say, nice, guy, youre, 40, jo..."
4,Lana Del Rey,Sirens,Bad Disease,2006,"Well, there's somethin' about watchin' a crime...",well theres somethin about watchin a crime tha...,"[well, there, somethin, watchin, crime, make, ..."

In [18]:
df.columns

Index(['artist', 'album', 'song', 'year', 'lyrics', 'basic_cleaned_lyrics',
       'nlp_cleaned_lyrics'],
      dtype='str')

# Add Basic features

In [19]:
basic_analyzer = LyricsFeatures(
    df,
    text_column="basic_cleaned_lyrics"
)

basic_analyzer.analyze()

df.columns

Index(['artist', 'album', 'song', 'year', 'lyrics', 'basic_cleaned_lyrics',
       'nlp_cleaned_lyrics', 'word_count', 'unique_words', 'syllable_count',
       'line_count', 'reading_minutes'],
      dtype='str')